package com.dead_comedian.farmerooni.entities.ai.data_stuff;

import net.minecraft.core.BlockPos;

import java.util.ArrayList;
import java.util.List;

/*
    Generic tree adapted from https://www.geeksforgeeks.org/dsa/introduction-to-tree-data-structure/
*/

public class Lumber {
    public BlockPos pos;
    public List<Lumber> neighbours;
    public Lumber parent;

    public Lumber(BlockPos x) {
        pos = x;
        neighbours = new ArrayList<>();
    }

    public Lumber(BlockPos x, Lumber Parent) {
        pos = x;
        parent = Parent;
        neighbours = new ArrayList<>();
    }

    public BlockPos Pos(){
        return this.pos;
    }

    public List<Lumber> Neighbours() {
        return this.neighbours;
    }

    public void addNeighbour(Lumber neighbourinquestion) {
        if(this.neighbours == null){
            neighbours = new ArrayList<>();
        }
        this.neighbours.add(neighbourinquestion);
    }

    public void removeNeighbour(Lumber neighbourinquestion) {
        this.neighbours.remove(neighbourinquestion);
    }

    public static boolean contains(Lumber node, BlockPos pos) {
        if(node == null || node.neighbours == null){
            return false;
        }
        if (node.pos.equals(pos))
            return true;

        for (Lumber child : node.neighbours) {
            if (contains(child, pos))
                return true;
        }

        return false;
    }
    public static Lumber root(Lumber node) {
        while (node.parent != null)
            node = node.parent;

        return node;
    }

    public static Lumber find(Lumber node, BlockPos pos) {
        if (node.pos.equals(pos))
            return node;

        for (Lumber child : node.neighbours) {
            Lumber found = find(child, pos);

            if (found != null)
                return found;
        }

        return null;
    }

    //not finna lie i had these two generated by duckai for debugging
    public static void printTree(Lumber root) {
        printTree(root, "", true);
    }

    private static void printTree(Lumber node, String prefix, boolean isLast) {
        if (node == null) {
            return;
        }
        if (node.neighbours == null) {
            return;
        }

        System.out.println(
                prefix +
                        (isLast ? "└── " : "├── ") +
                        node.pos
        );

        for (int i = 0; i < node.neighbours.size(); i++) {
            printTree(
                    node.neighbours.get(i),
                    prefix + (isLast ? "    " : "│   "),
                    i == node.neighbours.size() - 1
            );
        }
    }
}

