package com.dead_comedian.farmerooni.entities.ai.data_stuff;

import net.minecraft.core.BlockPos;

import java.util.ArrayList;
import java.util.List;

/*
    Generic tree adapted from https://www.geeksforgeeks.org/dsa/introduction-to-tree-data-structure/
*/

public class Tree {
    public BlockPos pos;
    public List<Tree> nodes;
    public Tree parent;

    public Tree(BlockPos x) {
        pos = x;
        nodes = new ArrayList<>();
    }

    public Tree(BlockPos x, Tree Parent) {
        pos = x;
        parent = Parent;
        nodes = new ArrayList<>();
    }

    public List<Tree> Nodes() {
        return this.nodes;
    }

    public void addNeighbour(Tree neighbourinquestion) {
        if (this.nodes == null) {
            nodes = new ArrayList<>();
        }
        this.nodes.add(neighbourinquestion);
    }

    public void removeNeighbour(Tree neighbourinquestion) {
        this.nodes.remove(neighbourinquestion);
    }

    public static boolean contains(Tree node, BlockPos pos) {
        if (node == null || node.nodes == null) {
            return false;
        }
        if (node.pos.equals(pos))
            return true;

        for (Tree child : node.nodes) {
            if (contains(child, pos))
                return true;
        }

        return false;
    }

    public static Tree root(Tree node) {
        while (node.parent != null)
            node = node.parent;

        return node;
    }

    public static Tree leaf(Tree node) {
        Tree child = node;
        while (!child.Nodes().isEmpty())
            child = child.Nodes().getFirst();

        return child;
    }

    public static Tree find(Tree node, BlockPos pos) {
        if (node.pos.equals(pos))
            return node;

        for (Tree child : node.nodes) {
            Tree found = find(child, pos);

            if (found != null)
                return found;
        }

        return null;
    }

    //not finna lie i had these two generated by duckai for debugging
    public static void printTree(Tree root) {
        printTree(root, "", true);
    }

    private static void printTree(Tree node, String prefix, boolean isLast) {
        if (node == null) {
            return;
        }
        if (node.nodes == null) {
            return;
        }

        System.out.println(
            prefix +
                (isLast ? "└── " : "├── ") +
                node.pos
        );

        for (int i = 0; i < node.nodes.size(); i++) {
            printTree(
                node.nodes.get(i),
                prefix + (isLast ? "    " : "│   "),
                i == node.nodes.size() - 1
            );
        }
    }
}

